module.exports = {
  btc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x0,
    scriptHash: 0x5,
    wif: 0x80,
  },
  btcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  arco: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x17,
    scriptHash: 0x5,
    wif: 0x97,
  },
  adc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x17,
    scriptHash: 0x7d,
    wif: 0x97,
  },
  adcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  bta: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x19,
    scriptHash: 0x5,
    wif: 0xbc,
  },
  btaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  bch: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x0,
    scriptHash: 0x5,
    wif: 0x80,
  },
  bchTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  btg: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x26,
    scriptHash: 0x17,
    wif: 0x80,
  },
  btgTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  btx: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x0,
    scriptHash: 0x5,
    wif: 0x80,
  },
  btxTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  btm: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x55,
    scriptHash: 0x5,
    wif: 0xd5,
  },
  bsd: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x66,
    scriptHash: 0x5,
    wif: 0xcc,
  },
  bsdTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  blk: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x19,
    scriptHash: 0x55,
    wif: 0x99,
  },
  block: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x1a,
    scriptHash: 0x1c,
    wif: 0x9a,
  },
  crea: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x1c,
    scriptHash: 0x5,
    wif: 0xb0,
  },
  creaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x57,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  dash: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x4c,
    scriptHash: 0x10,
    wif: 0xcc,
  },
  dashTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x8c,
    scriptHash: 0x13,
    wif: 0xef,
  },
  dgb: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x1e,
    scriptHash: 0x3f,
    wif: 0x80,
  },
  dope: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x1e,
    scriptHash: 0x5,
    wif: 0x9e,
  },
  efl: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x30,
    scriptHash: 0x5,
    wif: 0xb0,
  },
  eflTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  ent: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x21,
    scriptHash: 0x8,
    wif: 0x65,
  },
  entTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x5d,
    scriptHash: 0xa,
    wif: 0xef,
  },
  erc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x21,
    scriptHash: 0x5,
    wif: 0xa8,
  },
  gld: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x20,
    scriptHash: 0x5,
    wif: 0xa0,
  },
  gre: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x26,
    scriptHash: 0x55,
    wif: 0xa6,
  },
  gun: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x27,
    scriptHash: 0x5,
    wif: 0xa7,
  },
  i0c: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x69,
    scriptHash: 0x5,
    wif: 0x80,
  },
  ivc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x66,
    scriptHash: 0x5,
    wif: 0x75,
  },
  xjo: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x2b,
    scriptHash: 0xb,
    wif: 0x8f,
  },
  kmd: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3c,
    scriptHash: 0x55,
    wif: 0xbc,
  },
  lana: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x30,
    scriptHash: 0x5,
    wif: 0xb0,
  },
  lanaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  ltc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x30,
    scriptHash: 0x32,
    wif: 0xb0,
  },
  ltcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0x3a,
    wif: 0xef,
  },
  mac: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x5,
    wif: 0xb2,
  },
  macTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb2,
  },
  mona: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x5,
    wif: 0xb0,
  },
  monaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  mue: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x10,
    scriptHash: 0x4c,
    wif: 0x7e,
  },
  mueTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x26,
    scriptHash: 0x13,
    wif: 0x40,
  },
  moon: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3,
    scriptHash: 0x16,
    wif: 0x83,
  },
  xmy: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x9,
    wif: 0xb2,
  },
  xmyTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x58,
    scriptHash: 0xbc,
    wif: 0xef,
  },
  nav: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x55,
    wif: 0x96,
  },
  netko: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb1,
  },
  neva: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb1,
  },
  nevaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  part: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x38,
    scriptHash: 0x3c,
    wif: 0x6c,
  },
  partTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x76,
    scriptHash: 0x7a,
    wif: 0x2e,
  },
  ppc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x37,
    scriptHash: 0x75,
    wif: 0xb7,
  },
  ppcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  pura: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x37,
    scriptHash: 0x10,
    wif: 0x96,
  },
  qrk: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3a,
    scriptHash: 0x9,
    wif: 0xba,
  },
  qrkTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x77,
    scriptHash: 0xc7,
    wif: 0xf7,
  },
  rvn: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3c,
    scriptHash: 0x7a,
    wif: 0x80,
  },
  rvnTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  rby: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3c,
    scriptHash: 0x55,
    wif: 0xbc,
  },
  sxc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3e,
    scriptHash: 0x5,
    wif: 0xbe,
  },
  sxcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x7c,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  skc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0xc,
    wif: 0xe2,
  },
  slr: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x12,
    scriptHash: 0x5,
    wif: 0x92,
  },
  slrTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  bucks: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0x7d,
    wif: 0x99,
  },
  sys: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0x5,
    wif: 0xbf,
  },
  taj: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0x5,
    wif: 0x6f,
  },
  xto: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x42,
    scriptHash: 0x3,
    wif: 0x4c,
  },
  xtoTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x7f,
    scriptHash: 0x82,
    wif: 0x8a,
  },
  vtc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x5,
    wif: 0x80,
  },
  vtcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x4a,
    scriptHash: 0xc4,
    wif: 0xef,
  },
  via: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x21,
    wif: 0xc7,
  },
  viaTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x7f,
    scriptHash: 0xc4,
    wif: 0xff,
  },
  visio: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x7d,
    wif: 0xbf,
  },
  vivo: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x46,
    scriptHash: 0xa,
    wif: 0xc6,
  },
  xzc: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x52,
    scriptHash: 0x7,
    wif: 0xd2,
  },
  xzcTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0xb2,
    wif: 0xb9,
  },
  zet: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x50,
    scriptHash: 0x9,
    wif: 0xe0,
  },
  zetTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x58,
    scriptHash: 0xbc,
    wif: 0xef,
  },
  zoi: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x50,
    scriptHash: 0x7,
    wif: 0xd0,
  },
  zoiTest: {
    messagePrefix: '',
    bech32: '',
    bip32: {
      public: 0x0,
      private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0xb2,
    wif: 0xc1,
  },
};
