"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
const values_capnp_1 = require("./values.capnp");
exports._capnpFileId = "921d030365beff8c";
class Delta extends capnp_ts_1.Struct {
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getData(0, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKey(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(1, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Delta_" + super.toString(); }
}
Delta._capnp = { displayName: "Delta", id: "b36956d6aca4a098", size: new capnp_ts_1.ObjectSize(0, 2) };
exports.Delta = Delta;
class MetaData extends capnp_ts_1.Struct {
    adoptProof(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownProof() { return capnp_ts_1.Struct.disown(this.getProof()); }
    getProof() { return capnp_ts_1.Struct.getData(0, this); }
    hasProof() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProof(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setProof(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptSignature(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSignature() { return capnp_ts_1.Struct.disown(this.getSignature()); }
    getSignature() { return capnp_ts_1.Struct.getData(1, this); }
    hasSignature() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSignature(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setSignature(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getTimestamp() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setTimestamp(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    toString() { return "MetaData_" + super.toString(); }
}
MetaData._capnp = { displayName: "MetaData", id: "a70e205986d03e12", size: new capnp_ts_1.ObjectSize(8, 2) };
exports.MetaData = MetaData;
class TransactionPayload extends capnp_ts_1.Struct {
    adoptSender(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSender() { return capnp_ts_1.Struct.disown(this.getSender()); }
    getSender() { return capnp_ts_1.Struct.getData(0, this); }
    hasSender() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSender(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setSender(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptProcessor(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcessor() { return capnp_ts_1.Struct.disown(this.getProcessor()); }
    getProcessor() { return capnp_ts_1.Struct.getData(1, this); }
    hasProcessor() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcessor(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setProcessor(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getNonce() { return capnp_ts_1.Struct.getUint64(0, this); }
    setNonce(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getStampsSupplied() { return capnp_ts_1.Struct.getUint64(8, this); }
    setStampsSupplied(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getContractName() { return capnp_ts_1.Struct.getText(2, this); }
    setContractName(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getFunctionName() { return capnp_ts_1.Struct.getText(3, this); }
    setFunctionName(value) { capnp_ts_1.Struct.setText(3, value, this); }
    adoptKwargs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownKwargs() { return capnp_ts_1.Struct.disown(this.getKwargs()); }
    getKwargs() { return capnp_ts_1.Struct.getStruct(4, values_capnp_1.Map, this); }
    hasKwargs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initKwargs() { return capnp_ts_1.Struct.initStructAt(4, values_capnp_1.Map, this); }
    setKwargs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "TransactionPayload_" + super.toString(); }
}
TransactionPayload._capnp = { displayName: "TransactionPayload", id: "9da7e0d2cce0cea1", size: new capnp_ts_1.ObjectSize(16, 5) };
exports.TransactionPayload = TransactionPayload;
class Transaction extends capnp_ts_1.Struct {
    adoptMetadata(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMetadata() { return capnp_ts_1.Struct.disown(this.getMetadata()); }
    getMetadata() { return capnp_ts_1.Struct.getStruct(0, MetaData, this); }
    hasMetadata() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMetadata() { return capnp_ts_1.Struct.initStructAt(0, MetaData, this); }
    setMetadata(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptPayload(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPayload() { return capnp_ts_1.Struct.disown(this.getPayload()); }
    getPayload() { return capnp_ts_1.Struct.getStruct(1, TransactionPayload, this); }
    hasPayload() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPayload() { return capnp_ts_1.Struct.initStructAt(1, TransactionPayload, this); }
    setPayload(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Transaction_" + super.toString(); }
}
Transaction._capnp = { displayName: "Transaction", id: "f784dfdeb15a3120", size: new capnp_ts_1.ObjectSize(0, 2) };
exports.Transaction = Transaction;
class TransactionData extends capnp_ts_1.Struct {
    adoptTransaction(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTransaction() { return capnp_ts_1.Struct.disown(this.getTransaction()); }
    getTransaction() { return capnp_ts_1.Struct.getStruct(0, NewTransaction, this); }
    hasTransaction() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTransaction() { return capnp_ts_1.Struct.initStructAt(0, NewTransaction, this); }
    setTransaction(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getStatus() { return capnp_ts_1.Struct.getUint8(0, this); }
    setStatus(value) { capnp_ts_1.Struct.setUint8(0, value, this); }
    adoptState(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownState() { return capnp_ts_1.Struct.disown(this.getState()); }
    getState() { return capnp_ts_1.Struct.getList(1, TransactionData._State, this); }
    hasState() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initState(length) { return capnp_ts_1.Struct.initList(1, TransactionData._State, length, this); }
    setState(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getStampsUsed() { return capnp_ts_1.Struct.getUint64(8, this); }
    setStampsUsed(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "TransactionData_" + super.toString(); }
}
TransactionData._capnp = { displayName: "TransactionData", id: "a2d62360f4be217c", size: new capnp_ts_1.ObjectSize(16, 2) };
exports.TransactionData = TransactionData;
class Transactions extends capnp_ts_1.Struct {
    adoptTransactions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTransactions() { return capnp_ts_1.Struct.disown(this.getTransactions()); }
    getTransactions() { return capnp_ts_1.Struct.getList(0, Transactions._Transactions, this); }
    hasTransactions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTransactions(length) { return capnp_ts_1.Struct.initList(0, Transactions._Transactions, length, this); }
    setTransactions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Transactions_" + super.toString(); }
}
Transactions._capnp = { displayName: "Transactions", id: "bbfe7f501da387e9", size: new capnp_ts_1.ObjectSize(0, 1) };
exports.Transactions = Transactions;
class TransactionBatch extends capnp_ts_1.Struct {
    adoptTransactions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTransactions() { return capnp_ts_1.Struct.disown(this.getTransactions()); }
    getTransactions() { return capnp_ts_1.Struct.getList(0, TransactionBatch._Transactions, this); }
    hasTransactions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTransactions(length) { return capnp_ts_1.Struct.initList(0, TransactionBatch._Transactions, length, this); }
    setTransactions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getTimestamp() { return capnp_ts_1.Struct.getFloat64(0, this); }
    setTimestamp(value) { capnp_ts_1.Struct.setFloat64(0, value, this); }
    adoptSignature(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSignature() { return capnp_ts_1.Struct.disown(this.getSignature()); }
    getSignature() { return capnp_ts_1.Struct.getData(1, this); }
    hasSignature() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSignature(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setSignature(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptSender(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownSender() { return capnp_ts_1.Struct.disown(this.getSender()); }
    getSender() { return capnp_ts_1.Struct.getData(2, this); }
    hasSender() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initSender(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setSender(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptInputHash(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownInputHash() { return capnp_ts_1.Struct.disown(this.getInputHash()); }
    getInputHash() { return capnp_ts_1.Struct.getData(3, this); }
    hasInputHash() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initInputHash(length) { return capnp_ts_1.Struct.initData(3, length, this); }
    setInputHash(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "TransactionBatch_" + super.toString(); }
}
TransactionBatch._capnp = { displayName: "TransactionBatch", id: "b7fe07c9f4fa8a5b", size: new capnp_ts_1.ObjectSize(8, 4) };
exports.TransactionBatch = TransactionBatch;
class NewTransactionPayload extends capnp_ts_1.Struct {
    adoptSender(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSender() { return capnp_ts_1.Struct.disown(this.getSender()); }
    getSender() { return capnp_ts_1.Struct.getData(0, this); }
    hasSender() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSender(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setSender(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptProcessor(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownProcessor() { return capnp_ts_1.Struct.disown(this.getProcessor()); }
    getProcessor() { return capnp_ts_1.Struct.getData(1, this); }
    hasProcessor() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initProcessor(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setProcessor(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getNonce() { return capnp_ts_1.Struct.getUint64(0, this); }
    setNonce(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getStampsSupplied() { return capnp_ts_1.Struct.getUint64(8, this); }
    setStampsSupplied(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getContractName() { return capnp_ts_1.Struct.getText(2, this); }
    setContractName(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getFunctionName() { return capnp_ts_1.Struct.getText(3, this); }
    setFunctionName(value) { capnp_ts_1.Struct.setText(3, value, this); }
    adoptKwargs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownKwargs() { return capnp_ts_1.Struct.disown(this.getKwargs()); }
    getKwargs() { return capnp_ts_1.Struct.getData(4, this); }
    hasKwargs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initKwargs(length) { return capnp_ts_1.Struct.initData(4, length, this); }
    setKwargs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "NewTransactionPayload_" + super.toString(); }
}
NewTransactionPayload._capnp = { displayName: "NewTransactionPayload", id: "ea60ddf0049b6602", size: new capnp_ts_1.ObjectSize(16, 5) };
exports.NewTransactionPayload = NewTransactionPayload;
class NewTransaction extends capnp_ts_1.Struct {
    adoptMetadata(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMetadata() { return capnp_ts_1.Struct.disown(this.getMetadata()); }
    getMetadata() { return capnp_ts_1.Struct.getStruct(0, MetaData, this); }
    hasMetadata() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMetadata() { return capnp_ts_1.Struct.initStructAt(0, MetaData, this); }
    setMetadata(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptPayload(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPayload() { return capnp_ts_1.Struct.disown(this.getPayload()); }
    getPayload() { return capnp_ts_1.Struct.getStruct(1, NewTransactionPayload, this); }
    hasPayload() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPayload() { return capnp_ts_1.Struct.initStructAt(1, NewTransactionPayload, this); }
    setPayload(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "NewTransaction_" + super.toString(); }
}
NewTransaction._capnp = { displayName: "NewTransaction", id: "e27c9148999550e1", size: new capnp_ts_1.ObjectSize(0, 2) };
exports.NewTransaction = NewTransaction;
TransactionData._State = capnp.CompositeList(Delta);
Transactions._Transactions = capnp.CompositeList(Transaction);
TransactionBatch._Transactions = capnp.CompositeList(NewTransaction);
