module.exports = {
       BitcoinBTC: 
              {name: "Bitcoin",
              active: null,
              symbol: "BTC",
              balance: 5.12345678,
              icon: "/icons/tokens/BTC-c.svg",
              color: {color:"#f2a900"}},
       EthereumETH: 
              {name: "Ethereum",
              active: null,
              symbol: "ETH",
              balance: 12.12345678,
              icon: "/icons/tokens/ETH-c.svg",
              color: {color:"#3c3c3d"}},
       LitecoinLTC: 
              {name: "Litecoin",
              active: null,
              symbol: "LTC", 
              balance: 130.12345678, 
              icon: "/icons/tokens/LTC-c.svg", 
              color: {color:"#8d8d8d"}},
       "Bitcoin CashBCH": 
              {name: "Bitcoin Cash",
              active: null,  
              symbol: "BCH", 
              balance: 40.12345678, 
              icon: "/icons/tokens/BCH-alt-c.svg", 
              color: {color:"#ee8c28"}},
       "Bitcoin SVBSV": 
              {name: "Bitcoin SV",
              active: null,  
              symbol: "BSV", 
              balance: 86.12345678, 
              icon: "/icons/tokens/BTA-c.svg", 
              color: {color:"#EAB300"}},
       DashDASH:     
              {name: "Dash",
              active: null,  
              symbol: "DASH", 
              balance: 349.12345678, 
              icon: "/icons/tokens/DASH-c.svg", 
              color: {color:"#008de4"}},
       "Ethereum ClassicETC": 
              {name: "Ethereum Classic",
              active: null,  
              symbol: "ETC", 
              balance: 892.12345678, 
              icon: "/icons/tokens/ETC-c.svg", 
              color: {color:"#669073"}},
       VeChainVET:
              {name: "VeChain",
              active: null,  
              symbol: "VET", 
              balance: 10789.12345678, 
              icon: "/icons/tokens/VET-c.svg", 
              color: {color:"#23B3FA"}},
       AugurREP:
              {name: "Augur",
              active: null,
              symbol: "REP", 
              balance: 19287321.12345678, 
              icon: "/icons/tokens/REP-c.svg", 
              color: {color:"#553580"}},
};