"use strict";
/* tslint:disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
var capnp = require("capnp-ts");
var capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "921d030365beff8c";
var MetaData = /** @class */ (function (_super) {
    __extends(MetaData, _super);
    function MetaData() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    MetaData.prototype.adoptProof = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    MetaData.prototype.disownProof = function () { return capnp_ts_1.Struct.disown(this.getProof()); };
    MetaData.prototype.getProof = function () { return capnp_ts_1.Struct.getData(0, this); };
    MetaData.prototype.hasProof = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    MetaData.prototype.initProof = function (length) { return capnp_ts_1.Struct.initData(0, length, this); };
    MetaData.prototype.setProof = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    MetaData.prototype.adoptSignature = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    MetaData.prototype.disownSignature = function () { return capnp_ts_1.Struct.disown(this.getSignature()); };
    MetaData.prototype.getSignature = function () { return capnp_ts_1.Struct.getData(1, this); };
    MetaData.prototype.hasSignature = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    MetaData.prototype.initSignature = function (length) { return capnp_ts_1.Struct.initData(1, length, this); };
    MetaData.prototype.setSignature = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    MetaData.prototype.getTimestamp = function () { return capnp_ts_1.Struct.getFloat32(0, this); };
    MetaData.prototype.setTimestamp = function (value) { capnp_ts_1.Struct.setFloat32(0, value, this); };
    MetaData.prototype.toString = function () { return "MetaData_" + _super.prototype.toString.call(this); };
    MetaData._capnp = { displayName: "MetaData", id: "a70e205986d03e12", size: new capnp_ts_1.ObjectSize(8, 2) };
    return MetaData;
}(capnp_ts_1.Struct));
exports.MetaData = MetaData;
var ContractPayload = /** @class */ (function (_super) {
    __extends(ContractPayload, _super);
    function ContractPayload() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ContractPayload.prototype.getSender = function () { return capnp_ts_1.Struct.getText(0, this); };
    ContractPayload.prototype.setSender = function (value) { capnp_ts_1.Struct.setText(0, value, this); };
    ContractPayload.prototype.getNonce = function () { return capnp_ts_1.Struct.getText(1, this); };
    ContractPayload.prototype.setNonce = function (value) { capnp_ts_1.Struct.setText(1, value, this); };
    ContractPayload.prototype.getStampsSupplied = function () { return capnp_ts_1.Struct.getUint64(0, this); };
    ContractPayload.prototype.setStampsSupplied = function (value) { capnp_ts_1.Struct.setUint64(0, value, this); };
    ContractPayload.prototype.getContractName = function () { return capnp_ts_1.Struct.getText(2, this); };
    ContractPayload.prototype.setContractName = function (value) { capnp_ts_1.Struct.setText(2, value, this); };
    ContractPayload.prototype.getFunctionName = function () { return capnp_ts_1.Struct.getText(3, this); };
    ContractPayload.prototype.setFunctionName = function (value) { capnp_ts_1.Struct.setText(3, value, this); };
    ContractPayload.prototype.adoptKwargs = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); };
    ContractPayload.prototype.disownKwargs = function () { return capnp_ts_1.Struct.disown(this.getKwargs()); };
    ContractPayload.prototype.getKwargs = function () { return capnp_ts_1.Struct.getStruct(4, Map, this); };
    ContractPayload.prototype.hasKwargs = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); };
    ContractPayload.prototype.initKwargs = function () { return capnp_ts_1.Struct.initStructAt(4, Map, this); };
    ContractPayload.prototype.setKwargs = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); };
    ContractPayload.prototype.toString = function () { return "ContractPayload_" + _super.prototype.toString.call(this); };
    ContractPayload._capnp = { displayName: "ContractPayload", id: "a2f9223e3c957376", size: new capnp_ts_1.ObjectSize(8, 5) };
    return ContractPayload;
}(capnp_ts_1.Struct));
exports.ContractPayload = ContractPayload;
var ContractTransaction = /** @class */ (function (_super) {
    __extends(ContractTransaction, _super);
    function ContractTransaction() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ContractTransaction.prototype.adoptMetadata = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    ContractTransaction.prototype.disownMetadata = function () { return capnp_ts_1.Struct.disown(this.getMetadata()); };
    ContractTransaction.prototype.getMetadata = function () { return capnp_ts_1.Struct.getStruct(0, MetaData, this); };
    ContractTransaction.prototype.hasMetadata = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    ContractTransaction.prototype.initMetadata = function () { return capnp_ts_1.Struct.initStructAt(0, MetaData, this); };
    ContractTransaction.prototype.setMetadata = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    ContractTransaction.prototype.adoptPayload = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    ContractTransaction.prototype.disownPayload = function () { return capnp_ts_1.Struct.disown(this.getPayload()); };
    ContractTransaction.prototype.getPayload = function () { return capnp_ts_1.Struct.getData(1, this); };
    ContractTransaction.prototype.hasPayload = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    ContractTransaction.prototype.initPayload = function (length) { return capnp_ts_1.Struct.initData(1, length, this); };
    ContractTransaction.prototype.setPayload = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    ContractTransaction.prototype.toString = function () { return "ContractTransaction_" + _super.prototype.toString.call(this); };
    ContractTransaction._capnp = { displayName: "ContractTransaction", id: "ca37bc74f7386799", size: new capnp_ts_1.ObjectSize(0, 2) };
    return ContractTransaction;
}(capnp_ts_1.Struct));
exports.ContractTransaction = ContractTransaction;
var PublishPayload = /** @class */ (function (_super) {
    __extends(PublishPayload, _super);
    function PublishPayload() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    PublishPayload.prototype.getSender = function () { return capnp_ts_1.Struct.getText(0, this); };
    PublishPayload.prototype.setSender = function (value) { capnp_ts_1.Struct.setText(0, value, this); };
    PublishPayload.prototype.getNonce = function () { return capnp_ts_1.Struct.getText(1, this); };
    PublishPayload.prototype.setNonce = function (value) { capnp_ts_1.Struct.setText(1, value, this); };
    PublishPayload.prototype.getStampsSupplied = function () { return capnp_ts_1.Struct.getUint64(0, this); };
    PublishPayload.prototype.setStampsSupplied = function (value) { capnp_ts_1.Struct.setUint64(0, value, this); };
    PublishPayload.prototype.getContractName = function () { return capnp_ts_1.Struct.getText(2, this); };
    PublishPayload.prototype.setContractName = function (value) { capnp_ts_1.Struct.setText(2, value, this); };
    PublishPayload.prototype.getContractCode = function () { return capnp_ts_1.Struct.getText(3, this); };
    PublishPayload.prototype.setContractCode = function (value) { capnp_ts_1.Struct.setText(3, value, this); };
    PublishPayload.prototype.toString = function () { return "PublishPayload_" + _super.prototype.toString.call(this); };
    PublishPayload._capnp = { displayName: "PublishPayload", id: "fef088de36a4a4b0", size: new capnp_ts_1.ObjectSize(8, 4) };
    return PublishPayload;
}(capnp_ts_1.Struct));
exports.PublishPayload = PublishPayload;
var PublishTransaction = /** @class */ (function (_super) {
    __extends(PublishTransaction, _super);
    function PublishTransaction() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    PublishTransaction.prototype.adoptMetadata = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    PublishTransaction.prototype.disownMetadata = function () { return capnp_ts_1.Struct.disown(this.getMetadata()); };
    PublishTransaction.prototype.getMetadata = function () { return capnp_ts_1.Struct.getStruct(0, MetaData, this); };
    PublishTransaction.prototype.hasMetadata = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    PublishTransaction.prototype.initMetadata = function () { return capnp_ts_1.Struct.initStructAt(0, MetaData, this); };
    PublishTransaction.prototype.setMetadata = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    PublishTransaction.prototype.adoptPayload = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    PublishTransaction.prototype.disownPayload = function () { return capnp_ts_1.Struct.disown(this.getPayload()); };
    PublishTransaction.prototype.getPayload = function () { return capnp_ts_1.Struct.getData(1, this); };
    PublishTransaction.prototype.hasPayload = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    PublishTransaction.prototype.initPayload = function (length) { return capnp_ts_1.Struct.initData(1, length, this); };
    PublishTransaction.prototype.setPayload = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    PublishTransaction.prototype.toString = function () { return "PublishTransaction_" + _super.prototype.toString.call(this); };
    PublishTransaction._capnp = { displayName: "PublishTransaction", id: "9c18835ec6f5b892", size: new capnp_ts_1.ObjectSize(0, 2) };
    return PublishTransaction;
}(capnp_ts_1.Struct));
exports.PublishTransaction = PublishTransaction;
var TransactionData = /** @class */ (function (_super) {
    __extends(TransactionData, _super);
    function TransactionData() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    TransactionData.prototype.adoptContractTransaction = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionData.prototype.disownContractTransaction = function () { return capnp_ts_1.Struct.disown(this.getContractTransaction()); };
    TransactionData.prototype.getContractTransaction = function () { return capnp_ts_1.Struct.getStruct(0, ContractTransaction, this); };
    TransactionData.prototype.hasContractTransaction = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionData.prototype.initContractTransaction = function () { return capnp_ts_1.Struct.initStructAt(0, ContractTransaction, this); };
    TransactionData.prototype.setContractTransaction = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionData.prototype.getStatus = function () { return capnp_ts_1.Struct.getText(1, this); };
    TransactionData.prototype.setStatus = function (value) { capnp_ts_1.Struct.setText(1, value, this); };
    TransactionData.prototype.getState = function () { return capnp_ts_1.Struct.getText(2, this); };
    TransactionData.prototype.setState = function (value) { capnp_ts_1.Struct.setText(2, value, this); };
    TransactionData.prototype.getContractType = function () { return capnp_ts_1.Struct.getUint16(0, this); };
    TransactionData.prototype.setContractType = function (value) { capnp_ts_1.Struct.setUint16(0, value, this); };
    TransactionData.prototype.toString = function () { return "TransactionData_" + _super.prototype.toString.call(this); };
    TransactionData._capnp = { displayName: "TransactionData", id: "a2d62360f4be217c", size: new capnp_ts_1.ObjectSize(8, 3) };
    return TransactionData;
}(capnp_ts_1.Struct));
exports.TransactionData = TransactionData;
var Transactions = /** @class */ (function (_super) {
    __extends(Transactions, _super);
    function Transactions() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Transactions.prototype.adoptTransactions = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Transactions.prototype.disownTransactions = function () { return capnp_ts_1.Struct.disown(this.getTransactions()); };
    Transactions.prototype.getTransactions = function () { return capnp_ts_1.Struct.getList(0, capnp.DataList, this); };
    Transactions.prototype.hasTransactions = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Transactions.prototype.initTransactions = function (length) { return capnp_ts_1.Struct.initList(0, capnp.DataList, length, this); };
    Transactions.prototype.setTransactions = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Transactions.prototype.toString = function () { return "Transactions_" + _super.prototype.toString.call(this); };
    Transactions._capnp = { displayName: "Transactions", id: "bbfe7f501da387e9", size: new capnp_ts_1.ObjectSize(0, 1) };
    return Transactions;
}(capnp_ts_1.Struct));
exports.Transactions = Transactions;
var TransactionContainer = /** @class */ (function (_super) {
    __extends(TransactionContainer, _super);
    function TransactionContainer() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    TransactionContainer.prototype.getType = function () { return capnp_ts_1.Struct.getUint16(0, this); };
    TransactionContainer.prototype.setType = function (value) { capnp_ts_1.Struct.setUint16(0, value, this); };
    TransactionContainer.prototype.adoptPayload = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionContainer.prototype.disownPayload = function () { return capnp_ts_1.Struct.disown(this.getPayload()); };
    TransactionContainer.prototype.getPayload = function () { return capnp_ts_1.Struct.getData(0, this); };
    TransactionContainer.prototype.hasPayload = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionContainer.prototype.initPayload = function (length) { return capnp_ts_1.Struct.initData(0, length, this); };
    TransactionContainer.prototype.setPayload = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionContainer.prototype.toString = function () { return "TransactionContainer_" + _super.prototype.toString.call(this); };
    TransactionContainer._capnp = { displayName: "TransactionContainer", id: "e0df0e0be01dea86", size: new capnp_ts_1.ObjectSize(8, 1) };
    return TransactionContainer;
}(capnp_ts_1.Struct));
exports.TransactionContainer = TransactionContainer;
var OrderingContainer = /** @class */ (function (_super) {
    __extends(OrderingContainer, _super);
    function OrderingContainer() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    OrderingContainer.prototype.getType = function () { return capnp_ts_1.Struct.getUint16(0, this); };
    OrderingContainer.prototype.setType = function (value) { capnp_ts_1.Struct.setUint16(0, value, this); };
    OrderingContainer.prototype.adoptTransaction = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    OrderingContainer.prototype.disownTransaction = function () { return capnp_ts_1.Struct.disown(this.getTransaction()); };
    OrderingContainer.prototype.getTransaction = function () { return capnp_ts_1.Struct.getData(0, this); };
    OrderingContainer.prototype.hasTransaction = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    OrderingContainer.prototype.initTransaction = function (length) { return capnp_ts_1.Struct.initData(0, length, this); };
    OrderingContainer.prototype.setTransaction = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    OrderingContainer.prototype.getUtcTimeMs = function () { return capnp_ts_1.Struct.getUint64(8, this); };
    OrderingContainer.prototype.setUtcTimeMs = function (value) { capnp_ts_1.Struct.setUint64(8, value, this); };
    OrderingContainer.prototype.toString = function () { return "OrderingContainer_" + _super.prototype.toString.call(this); };
    OrderingContainer._capnp = { displayName: "OrderingContainer", id: "8c0e979c553fd93f", size: new capnp_ts_1.ObjectSize(16, 1) };
    return OrderingContainer;
}(capnp_ts_1.Struct));
exports.OrderingContainer = OrderingContainer;
var TransactionBatch = /** @class */ (function (_super) {
    __extends(TransactionBatch, _super);
    function TransactionBatch() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    TransactionBatch.prototype.adoptTransactions = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionBatch.prototype.disownTransactions = function () { return capnp_ts_1.Struct.disown(this.getTransactions()); };
    TransactionBatch.prototype.getTransactions = function () { return capnp_ts_1.Struct.getList(0, TransactionBatch._Transactions, this); };
    TransactionBatch.prototype.hasTransactions = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionBatch.prototype.initTransactions = function (length) { return capnp_ts_1.Struct.initList(0, TransactionBatch._Transactions, length, this); };
    TransactionBatch.prototype.setTransactions = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    TransactionBatch.prototype.toString = function () { return "TransactionBatch_" + _super.prototype.toString.call(this); };
    TransactionBatch._capnp = { displayName: "TransactionBatch", id: "b7fe07c9f4fa8a5b", size: new capnp_ts_1.ObjectSize(0, 1) };
    return TransactionBatch;
}(capnp_ts_1.Struct));
exports.TransactionBatch = TransactionBatch;
var StandardTransaction_Payload = /** @class */ (function (_super) {
    __extends(StandardTransaction_Payload, _super);
    function StandardTransaction_Payload() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    StandardTransaction_Payload.prototype.adoptSender = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction_Payload.prototype.disownSender = function () { return capnp_ts_1.Struct.disown(this.getSender()); };
    StandardTransaction_Payload.prototype.getSender = function () { return capnp_ts_1.Struct.getData(0, this); };
    StandardTransaction_Payload.prototype.hasSender = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction_Payload.prototype.initSender = function (length) { return capnp_ts_1.Struct.initData(0, length, this); };
    StandardTransaction_Payload.prototype.setSender = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction_Payload.prototype.adoptReceiver = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction_Payload.prototype.disownReceiver = function () { return capnp_ts_1.Struct.disown(this.getReceiver()); };
    StandardTransaction_Payload.prototype.getReceiver = function () { return capnp_ts_1.Struct.getData(1, this); };
    StandardTransaction_Payload.prototype.hasReceiver = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction_Payload.prototype.initReceiver = function (length) { return capnp_ts_1.Struct.initData(1, length, this); };
    StandardTransaction_Payload.prototype.setReceiver = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction_Payload.prototype.getAmount = function () { return capnp_ts_1.Struct.getUint64(0, this); };
    StandardTransaction_Payload.prototype.setAmount = function (value) { capnp_ts_1.Struct.setUint64(0, value, this); };
    StandardTransaction_Payload.prototype.toString = function () { return "StandardTransaction_Payload_" + _super.prototype.toString.call(this); };
    StandardTransaction_Payload._capnp = { displayName: "Payload", id: "da2bd110e8191c10", size: new capnp_ts_1.ObjectSize(8, 2) };
    return StandardTransaction_Payload;
}(capnp_ts_1.Struct));
exports.StandardTransaction_Payload = StandardTransaction_Payload;
var StandardTransaction = /** @class */ (function (_super) {
    __extends(StandardTransaction, _super);
    function StandardTransaction() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    StandardTransaction.prototype.adoptMetadata = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction.prototype.disownMetadata = function () { return capnp_ts_1.Struct.disown(this.getMetadata()); };
    StandardTransaction.prototype.getMetadata = function () { return capnp_ts_1.Struct.getStruct(0, MetaData, this); };
    StandardTransaction.prototype.hasMetadata = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction.prototype.initMetadata = function () { return capnp_ts_1.Struct.initStructAt(0, MetaData, this); };
    StandardTransaction.prototype.setMetadata = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    StandardTransaction.prototype.adoptPayload = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction.prototype.disownPayload = function () { return capnp_ts_1.Struct.disown(this.getPayload()); };
    StandardTransaction.prototype.getPayload = function () { return capnp_ts_1.Struct.getStruct(1, StandardTransaction_Payload, this); };
    StandardTransaction.prototype.hasPayload = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction.prototype.initPayload = function () { return capnp_ts_1.Struct.initStructAt(1, StandardTransaction_Payload, this); };
    StandardTransaction.prototype.setPayload = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    StandardTransaction.prototype.toString = function () { return "StandardTransaction_" + _super.prototype.toString.call(this); };
    StandardTransaction.Payload = StandardTransaction_Payload;
    StandardTransaction._capnp = { displayName: "StandardTransaction", id: "b7524d22a62ea1c9", size: new capnp_ts_1.ObjectSize(0, 2) };
    return StandardTransaction;
}(capnp_ts_1.Struct));
exports.StandardTransaction = StandardTransaction;
var Value_Which;
(function (Value_Which) {
    Value_Which[Value_Which["VOID"] = 0] = "VOID";
    Value_Which[Value_Which["BOOL"] = 1] = "BOOL";
    Value_Which[Value_Which["INT8"] = 2] = "INT8";
    Value_Which[Value_Which["INT16"] = 3] = "INT16";
    Value_Which[Value_Which["INT32"] = 4] = "INT32";
    Value_Which[Value_Which["INT64"] = 5] = "INT64";
    Value_Which[Value_Which["UINT8"] = 6] = "UINT8";
    Value_Which[Value_Which["UINT16"] = 7] = "UINT16";
    Value_Which[Value_Which["UINT32"] = 8] = "UINT32";
    Value_Which[Value_Which["UINT64"] = 9] = "UINT64";
    Value_Which[Value_Which["FIXED_POINT"] = 10] = "FIXED_POINT";
    Value_Which[Value_Which["FLOAT32"] = 11] = "FLOAT32";
    Value_Which[Value_Which["FLOAT64"] = 12] = "FLOAT64";
    Value_Which[Value_Which["TEXT"] = 13] = "TEXT";
    Value_Which[Value_Which["DATA"] = 14] = "DATA";
    Value_Which[Value_Which["LIST"] = 15] = "LIST";
    Value_Which[Value_Which["ENUM"] = 16] = "ENUM";
    Value_Which[Value_Which["STRUCT"] = 17] = "STRUCT";
    Value_Which[Value_Which["ANY_POINTER"] = 18] = "ANY_POINTER";
})(Value_Which = exports.Value_Which || (exports.Value_Which = {}));
var Value = /** @class */ (function (_super) {
    __extends(Value, _super);
    function Value() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Value.prototype.isVoid = function () { return capnp_ts_1.Struct.getUint16(0, this) === 0; };
    Value.prototype.setVoid = function () { capnp_ts_1.Struct.setUint16(0, 0, this); };
    Value.prototype.getBool = function () {
        capnp_ts_1.Struct.testWhich("bool", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getBit(16, this);
    };
    Value.prototype.isBool = function () { return capnp_ts_1.Struct.getUint16(0, this) === 1; };
    Value.prototype.setBool = function (value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.setBit(16, value, this);
    };
    Value.prototype.getInt8 = function () {
        capnp_ts_1.Struct.testWhich("int8", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getInt8(2, this);
    };
    Value.prototype.isInt8 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 2; };
    Value.prototype.setInt8 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setInt8(2, value, this);
    };
    Value.prototype.getInt16 = function () {
        capnp_ts_1.Struct.testWhich("int16", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getInt16(2, this);
    };
    Value.prototype.isInt16 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 3; };
    Value.prototype.setInt16 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.setInt16(2, value, this);
    };
    Value.prototype.getInt32 = function () {
        capnp_ts_1.Struct.testWhich("int32", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getInt32(4, this);
    };
    Value.prototype.isInt32 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 4; };
    Value.prototype.setInt32 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.setInt32(4, value, this);
    };
    Value.prototype.getInt64 = function () {
        capnp_ts_1.Struct.testWhich("int64", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getInt64(8, this);
    };
    Value.prototype.isInt64 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 5; };
    Value.prototype.setInt64 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.setInt64(8, value, this);
    };
    Value.prototype.getUint8 = function () {
        capnp_ts_1.Struct.testWhich("uint8", capnp_ts_1.Struct.getUint16(0, this), 6, this);
        return capnp_ts_1.Struct.getUint8(2, this);
    };
    Value.prototype.isUint8 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 6; };
    Value.prototype.setUint8 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.setUint8(2, value, this);
    };
    Value.prototype.getUint16 = function () {
        capnp_ts_1.Struct.testWhich("uint16", capnp_ts_1.Struct.getUint16(0, this), 7, this);
        return capnp_ts_1.Struct.getUint16(2, this);
    };
    Value.prototype.isUint16 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 7; };
    Value.prototype.setUint16 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.setUint16(2, value, this);
    };
    Value.prototype.getUint32 = function () {
        capnp_ts_1.Struct.testWhich("uint32", capnp_ts_1.Struct.getUint16(0, this), 8, this);
        return capnp_ts_1.Struct.getUint32(4, this);
    };
    Value.prototype.isUint32 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 8; };
    Value.prototype.setUint32 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.setUint32(4, value, this);
    };
    Value.prototype.getUint64 = function () {
        capnp_ts_1.Struct.testWhich("uint64", capnp_ts_1.Struct.getUint16(0, this), 9, this);
        return capnp_ts_1.Struct.getUint64(8, this);
    };
    Value.prototype.isUint64 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 9; };
    Value.prototype.setUint64 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.setUint64(8, value, this);
    };
    Value.prototype.getFixedPoint = function () {
        capnp_ts_1.Struct.testWhich("fixedPoint", capnp_ts_1.Struct.getUint16(0, this), 10, this);
        return capnp_ts_1.Struct.getText(0, this);
    };
    Value.prototype.isFixedPoint = function () { return capnp_ts_1.Struct.getUint16(0, this) === 10; };
    Value.prototype.setFixedPoint = function (value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.setText(0, value, this);
    };
    Value.prototype.getFloat32 = function () {
        capnp_ts_1.Struct.testWhich("float32", capnp_ts_1.Struct.getUint16(0, this), 11, this);
        return capnp_ts_1.Struct.getFloat32(4, this);
    };
    Value.prototype.isFloat32 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 11; };
    Value.prototype.setFloat32 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.setFloat32(4, value, this);
    };
    Value.prototype.getFloat64 = function () {
        capnp_ts_1.Struct.testWhich("float64", capnp_ts_1.Struct.getUint16(0, this), 12, this);
        return capnp_ts_1.Struct.getFloat64(8, this);
    };
    Value.prototype.isFloat64 = function () { return capnp_ts_1.Struct.getUint16(0, this) === 12; };
    Value.prototype.setFloat64 = function (value) {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        capnp_ts_1.Struct.setFloat64(8, value, this);
    };
    Value.prototype.getText = function () {
        capnp_ts_1.Struct.testWhich("text", capnp_ts_1.Struct.getUint16(0, this), 13, this);
        return capnp_ts_1.Struct.getText(0, this);
    };
    Value.prototype.isText = function () { return capnp_ts_1.Struct.getUint16(0, this) === 13; };
    Value.prototype.setText = function (value) {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        capnp_ts_1.Struct.setText(0, value, this);
    };
    Value.prototype.adoptData = function (value) {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.disownData = function () { return capnp_ts_1.Struct.disown(this.getData()); };
    Value.prototype.getData = function () {
        capnp_ts_1.Struct.testWhich("data", capnp_ts_1.Struct.getUint16(0, this), 14, this);
        return capnp_ts_1.Struct.getData(0, this);
    };
    Value.prototype.hasData = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Value.prototype.initData = function (length) {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        return capnp_ts_1.Struct.initData(0, length, this);
    };
    Value.prototype.isData = function () { return capnp_ts_1.Struct.getUint16(0, this) === 14; };
    Value.prototype.setData = function (value) {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.adoptList = function (value) {
        capnp_ts_1.Struct.setUint16(0, 15, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.disownList = function () { return capnp_ts_1.Struct.disown(this.getList()); };
    Value.prototype.getList = function () {
        capnp_ts_1.Struct.testWhich("list", capnp_ts_1.Struct.getUint16(0, this), 15, this);
        return capnp_ts_1.Struct.getPointer(0, this);
    };
    Value.prototype.hasList = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Value.prototype.isList = function () { return capnp_ts_1.Struct.getUint16(0, this) === 15; };
    Value.prototype.setList = function (value) {
        capnp_ts_1.Struct.setUint16(0, 15, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.getEnum = function () {
        capnp_ts_1.Struct.testWhich("enum", capnp_ts_1.Struct.getUint16(0, this), 16, this);
        return capnp_ts_1.Struct.getUint16(2, this);
    };
    Value.prototype.isEnum = function () { return capnp_ts_1.Struct.getUint16(0, this) === 16; };
    Value.prototype.setEnum = function (value) {
        capnp_ts_1.Struct.setUint16(0, 16, this);
        capnp_ts_1.Struct.setUint16(2, value, this);
    };
    Value.prototype.adoptStruct = function (value) {
        capnp_ts_1.Struct.setUint16(0, 17, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.disownStruct = function () { return capnp_ts_1.Struct.disown(this.getStruct()); };
    Value.prototype.getStruct = function () {
        capnp_ts_1.Struct.testWhich("struct", capnp_ts_1.Struct.getUint16(0, this), 17, this);
        return capnp_ts_1.Struct.getPointer(0, this);
    };
    Value.prototype.hasStruct = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Value.prototype.isStruct = function () { return capnp_ts_1.Struct.getUint16(0, this) === 17; };
    Value.prototype.setStruct = function (value) {
        capnp_ts_1.Struct.setUint16(0, 17, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.adoptAnyPointer = function (value) {
        capnp_ts_1.Struct.setUint16(0, 18, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.disownAnyPointer = function () { return capnp_ts_1.Struct.disown(this.getAnyPointer()); };
    Value.prototype.getAnyPointer = function () {
        capnp_ts_1.Struct.testWhich("anyPointer", capnp_ts_1.Struct.getUint16(0, this), 18, this);
        return capnp_ts_1.Struct.getPointer(0, this);
    };
    Value.prototype.hasAnyPointer = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Value.prototype.isAnyPointer = function () { return capnp_ts_1.Struct.getUint16(0, this) === 18; };
    Value.prototype.setAnyPointer = function (value) {
        capnp_ts_1.Struct.setUint16(0, 18, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    };
    Value.prototype.toString = function () { return "Value_" + _super.prototype.toString.call(this); };
    Value.prototype.which = function () { return capnp_ts_1.Struct.getUint16(0, this); };
    Value.VOID = Value_Which.VOID;
    Value.BOOL = Value_Which.BOOL;
    Value.INT8 = Value_Which.INT8;
    Value.INT16 = Value_Which.INT16;
    Value.INT32 = Value_Which.INT32;
    Value.INT64 = Value_Which.INT64;
    Value.UINT8 = Value_Which.UINT8;
    Value.UINT16 = Value_Which.UINT16;
    Value.UINT32 = Value_Which.UINT32;
    Value.UINT64 = Value_Which.UINT64;
    Value.FIXED_POINT = Value_Which.FIXED_POINT;
    Value.FLOAT32 = Value_Which.FLOAT32;
    Value.FLOAT64 = Value_Which.FLOAT64;
    Value.TEXT = Value_Which.TEXT;
    Value.DATA = Value_Which.DATA;
    Value.LIST = Value_Which.LIST;
    Value.ENUM = Value_Which.ENUM;
    Value.STRUCT = Value_Which.STRUCT;
    Value.ANY_POINTER = Value_Which.ANY_POINTER;
    Value._capnp = { displayName: "Value", id: "9ef507019559fb0e", size: new capnp_ts_1.ObjectSize(16, 1) };
    return Value;
}(capnp_ts_1.Struct));
exports.Value = Value;
var Map_Entry = /** @class */ (function (_super) {
    __extends(Map_Entry, _super);
    function Map_Entry() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Map_Entry.prototype.getKey = function () { return capnp_ts_1.Struct.getText(0, this); };
    Map_Entry.prototype.setKey = function (value) { capnp_ts_1.Struct.setText(0, value, this); };
    Map_Entry.prototype.adoptValue = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); };
    Map_Entry.prototype.disownValue = function () { return capnp_ts_1.Struct.disown(this.getValue()); };
    Map_Entry.prototype.getValue = function () { return capnp_ts_1.Struct.getPointer(1, this); };
    Map_Entry.prototype.hasValue = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); };
    Map_Entry.prototype.setValue = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); };
    Map_Entry.prototype.toString = function () { return "Map_Entry_" + _super.prototype.toString.call(this); };
    Map_Entry._capnp = { displayName: "Entry", id: "d1e642fa99ec5acc", size: new capnp_ts_1.ObjectSize(0, 2) };
    return Map_Entry;
}(capnp_ts_1.Struct));
exports.Map_Entry = Map_Entry;
var Map = /** @class */ (function (_super) {
    __extends(Map, _super);
    function Map() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Map.prototype.adoptEntries = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Map.prototype.disownEntries = function () { return capnp_ts_1.Struct.disown(this.getEntries()); };
    Map.prototype.getEntries = function () { return capnp_ts_1.Struct.getList(0, Map._Entries, this); };
    Map.prototype.hasEntries = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Map.prototype.initEntries = function (length) { return capnp_ts_1.Struct.initList(0, Map._Entries, length, this); };
    Map.prototype.setEntries = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Map.prototype.toString = function () { return "Map_" + _super.prototype.toString.call(this); };
    Map.Entry = Map_Entry;
    Map._capnp = { displayName: "Map", id: "a97da21d048f7797", size: new capnp_ts_1.ObjectSize(0, 1) };
    return Map;
}(capnp_ts_1.Struct));
exports.Map = Map;
var Kwargs = /** @class */ (function (_super) {
    __extends(Kwargs, _super);
    function Kwargs() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Kwargs.prototype.adoptKwargs = function (value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Kwargs.prototype.disownKwargs = function () { return capnp_ts_1.Struct.disown(this.getKwargs()); };
    Kwargs.prototype.getKwargs = function () { return capnp_ts_1.Struct.getStruct(0, Map, this); };
    Kwargs.prototype.hasKwargs = function () { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); };
    Kwargs.prototype.initKwargs = function () { return capnp_ts_1.Struct.initStructAt(0, Map, this); };
    Kwargs.prototype.setKwargs = function (value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); };
    Kwargs.prototype.toString = function () { return "Kwargs_" + _super.prototype.toString.call(this); };
    Kwargs._capnp = { displayName: "Kwargs", id: "c803c0184eb67ef2", size: new capnp_ts_1.ObjectSize(0, 1) };
    return Kwargs;
}(capnp_ts_1.Struct));
exports.Kwargs = Kwargs;
TransactionBatch._Transactions = capnp.CompositeList(OrderingContainer);
Map._Entries = capnp.CompositeList(Map_Entry);
