const ethereum = {
    ETH : { chainID: 1 },
    'ETH-TESTNET' : { chainID: 42 },
    EGEM : { chainID: 1987 },
}

const bitcoin = {
    BTC: {
        messagePrefix: '',
        bech32: '',
        bip32: {
          public: 0x0,
          private: 0x0,
        },
        pubKeyHash: 0x0,
        scriptHash: 0x5,
        wif: 0x80,
      },
    'BTC-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    ARCO: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x17,
        scriptHash: 0x5,
        wif: 0x97,
    },
    ADC: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x17,
        scriptHash: 0x7d,
        wif: 0x97,
    },
    'ADC-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    BTA: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x19,
        scriptHash: 0x5,
        wif: 0xbc,
    },
    'BTA-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    BTG: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x26,
        scriptHash: 0x17,
        wif: 0x80,
    },
    'BTG-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    BTX: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x0,
        scriptHash: 0x5,
        wif: 0x80,
    },
    'BTX-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    BTM: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x55,
        scriptHash: 0x5,
        wif: 0xd5,
    },
    BSD: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x66,
        scriptHash: 0x5,
        wif: 0xcc,
    },
    'BSD-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    BLK: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x19,
        scriptHash: 0x55,
        wif: 0x99,
    },
    BLOCK: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x1a,
        scriptHash: 0x1c,
        wif: 0x9a,
    },
    CREA: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x1c,
        scriptHash: 0x5,
        wif: 0xb0,
    },
    'CREA-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x57,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    DASH: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x4c,
        scriptHash: 0x10,
        wif: 0xcc,
    },
    'DASH-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x8c,
        scriptHash: 0x13,
        wif: 0xef,
    },
    DGB: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x1e,
        scriptHash: 0x3f,
        wif: 0x80,
    },
    DOPE: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x1e,
        scriptHash: 0x5,
        wif: 0x9e,
    },
    EFL: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x30,
        scriptHash: 0x5,
        wif: 0xb0,
    },
    'EFL-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x6f,
        scriptHash: 0xc4,
        wif: 0xef,
    },
    ENT: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x21,
        scriptHash: 0x8,
        wif: 0x65,
    },
    'ENT-TESTNET': {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x5d,
        scriptHash: 0xa,
        wif: 0xef,
    },
    ERC: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x21,
        scriptHash: 0x5,
        wif: 0xa8,
    },
    GLD: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x20,
        scriptHash: 0x5,
        wif: 0xa0,
    },
    GRE: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x26,
        scriptHash: 0x55,
        wif: 0xa6,
    },
    GUN: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x27,
        scriptHash: 0x5,
        wif: 0xa7,
    },
    I0C: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x69,
        scriptHash: 0x5,
        wif: 0x80,
    },
    IVC: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x66,
        scriptHash: 0x5,
        wif: 0x75,
    },
    XJO: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x2b,
        scriptHash: 0xb,
        wif: 0x8f,
    },
    KMD: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x3c,
        scriptHash: 0x55,
        wif: 0xbc,
    },
    LANA: {
        messagePrefix: '',
        bech32: '',
        bip32: {
            public: 0x0,
            private: 0x0,
        },
        pubKeyHash: 0x30,
        scriptHash: 0x5,
        wif: 0xb0,
    },
    'LANA-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    LTC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x30,
    scriptHash: 0x32,
    wif: 0xb0,
    },
    'LTC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0x3a,
    wif: 0xef,
    },
    MAC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x5,
    wif: 0xb2,
    },
    'MAC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb2,
    },
    MONA: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x5,
    wif: 0xb0,
    },
    'MONA-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    MUE: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x10,
    scriptHash: 0x4c,
    wif: 0x7e,
    },
    'MUE-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x26,
    scriptHash: 0x13,
    wif: 0x40,
    },
    MOON: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3,
    scriptHash: 0x16,
    wif: 0x83,
    },
    XMY: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x32,
    scriptHash: 0x9,
    wif: 0xb2,
    },
    'XMY-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x58,
    scriptHash: 0xbc,
    wif: 0xef,
    },
    NAV: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x55,
    wif: 0x96,
    },
    NETKO: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb1,
    },
    NEVA: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x35,
    scriptHash: 0x5,
    wif: 0xb1,
    },
    'NEVA-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    PART: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x38,
    scriptHash: 0x3c,
    wif: 0x6c,
    },
    'PART-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x76,
    scriptHash: 0x7a,
    wif: 0x2e,
    },
    PPC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x37,
    scriptHash: 0x75,
    wif: 0xb7,
    },
    'PPC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    PURA: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x37,
    scriptHash: 0x10,
    wif: 0x96,
    },
    QRK: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3a,
    scriptHash: 0x9,
    wif: 0xba,
    },
    'QRK-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x77,
    scriptHash: 0xc7,
    wif: 0xf7,
    },
    RVN: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3c,
    scriptHash: 0x7a,
    wif: 0x80,
    },
    'RVN-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    RBY: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3c,
    scriptHash: 0x55,
    wif: 0xbc,
    },
    SXC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3e,
    scriptHash: 0x5,
    wif: 0xbe,
    },
    'SXC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x7c,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    SKC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0xc,
    wif: 0xe2,
    },
    SLR: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x12,
    scriptHash: 0x5,
    wif: 0x92,
    },
    'SLR-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x6f,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    BUCKS: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0x7d,
    wif: 0x99,
    },
    SYS: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x3f,
    scriptHash: 0x5,
    wif: 0xbf,
    },
    TAJ: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0x5,
    wif: 0x6f,
    },
    XTO: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x42,
    scriptHash: 0x3,
    wif: 0x4c,
    },
    'XTO-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x7f,
    scriptHash: 0x82,
    wif: 0x8a,
    },
    VTC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x5,
    wif: 0x80,
    },
    'VTC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x4a,
    scriptHash: 0xc4,
    wif: 0xef,
    },
    VIA: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x21,
    wif: 0xc7,
    },
    'VIA-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x7f,
    scriptHash: 0xc4,
    wif: 0xff,
    },
    VISIO: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x47,
    scriptHash: 0x7d,
    wif: 0xbf,
    },
    VIVO: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x46,
    scriptHash: 0xa,
    wif: 0xc6,
    },
    XZC: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x52,
    scriptHash: 0x7,
    wif: 0xd2,
    },
    'XZC-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0xb2,
    wif: 0xb9,
    },
    ZET: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x50,
    scriptHash: 0x9,
    wif: 0xe0,
    },
    'ZET-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x58,
    scriptHash: 0xbc,
    wif: 0xef,
    },
    ZOI: {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x50,
    scriptHash: 0x7,
    wif: 0xd0,
    },
    'ZOI-TESTNET': {
    messagePrefix: '',
    bech32: '',
    bip32: {
        public: 0x0,
        private: 0x0,
    },
    pubKeyHash: 0x41,
    scriptHash: 0xb2,
    wif: 0xc1,
    },
};

module.exports = {
    ethereum, 
    bitcoin
};